//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactenos
    {
        public int idcon { get; set; }
        public string nomcompcon { get; set; }
        public string dnicon { get; set; }
        public string corcon { get; set; }
        public string telcon { get; set; }
        public string celcon { get; set; }
        public string empcon { get; set; }
        public string comcon { get; set; }
    }
}
