//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRV_PASAJERO
    {
        public int CODPAS { get; set; }
        public string NOMPAS { get; set; }
        public string APEPPAS { get; set; }
        public string APEMPAS { get; set; }
        public string DIRPAS { get; set; }
        public string SEXPAS { get; set; }
        public string CELPAS { get; set; }
        public string TELPAS { get; set; }
        public string ESTREG { get; set; }
        public string ESTTRAN { get; set; }
        public Nullable<int> CODRES { get; set; }
        public string TIPDOC { get; set; }
        public string NUMDOC { get; set; }
        public string NUMASI { get; set; }
        public string TIPVIA { get; set; }
    }
}
