//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRV_CUPONES
    {
        public int CODCUP { get; set; }
        public Nullable<decimal> PORDESC { get; set; }
        public string ESTREG { get; set; }
        public Nullable<System.DateTime> FECVIG { get; set; }
        public Nullable<int> CODCLI { get; set; }
    }
}
