//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRV_RESERVA
    {
        public SRV_RESERVA()
        {
            this.SRV_COMPRA = new HashSet<SRV_COMPRA>();
        }
    
        public int CODRES { get; set; }
        public Nullable<System.DateTime> FECRES { get; set; }
        public string ESTREG { get; set; }
        public string ESTTRAN { get; set; }
        public Nullable<int> CODCLI { get; set; }
        public Nullable<int> CODPRO { get; set; }
        public Nullable<int> CODPRODES { get; set; }
    
        public virtual ICollection<SRV_COMPRA> SRV_COMPRA { get; set; }
    }
}
