//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRV_PERSONAL
    {
        public int CODPER { get; set; }
        public string NOMPER { get; set; }
        public string APEPER { get; set; }
        public string DNIPER { get; set; }
        public string ESTREG { get; set; }
        public Nullable<int> CODUSU { get; set; }
    }
}
