//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRV_PROGRAMACION
    {
        public int CODPRO { get; set; }
        public Nullable<System.DateTime> FECSALPRO { get; set; }
        public string HORSALPRO { get; set; }
        public string ESTREG { get; set; }
        public Nullable<int> CODBUS { get; set; }
        public Nullable<int> CODTAR { get; set; }
        public Nullable<int> CODPROM { get; set; }
    }
}
