//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRV_VW_ASIENTOS_RESERVADOSDES
    {
        public int CODPAS { get; set; }
        public int CODPRO { get; set; }
        public string NUMASI { get; set; }
    }
}
