//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRV_TARIFA
    {
        public int CODTAR { get; set; }
        public string ORITAR { get; set; }
        public string DESTAR { get; set; }
        public Nullable<decimal> PRETAR { get; set; }
        public string ESTREG { get; set; }
        public Nullable<int> CODTIPSER { get; set; }
        public string CODESTTAR { get; set; }
    }
}
