//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRV_BUS
    {
        public int CODBUS { get; set; }
        public string PLABUS { get; set; }
        public string ANIOBUS { get; set; }
        public Nullable<int> NROEJE { get; set; }
        public string ESTREG { get; set; }
        public Nullable<int> CODTIPSER { get; set; }
    }
}
