//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRV_TIPO_TARJETA
    {
        public SRV_TIPO_TARJETA()
        {
            this.SRV_TARJETA = new HashSet<SRV_TARJETA>();
        }
    
        public int CODTIPTAR { get; set; }
        public string NOMTIPTAR { get; set; }
        public string ESTREG { get; set; }
        public string MEDPAG { get; set; }
    
        public virtual ICollection<SRV_TARJETA> SRV_TARJETA { get; set; }
    }
}
